# FORGE Platform - Lambda CI/CD Pipeline
# Epic 9: Infrastructure
# Task 9.4.7: Lambda CI/CD Pipeline
#
# Features:
# - Build Lambda deployment packages
# - Upload to S3
# - Update Lambda function code
# - Run smoke tests
# - Rollback on failure

name: Deploy FORGE Lambda Functions

on:
  push:
    branches: [main]
    paths:
      - 'infrastructure/lambda/**'
      - 'infrastructure/terraform/modules/lambda/**'
  pull_request:
    branches: [main]
    paths:
      - 'infrastructure/lambda/**'
      - 'infrastructure/terraform/modules/lambda/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - prod
      skip_tests:
        description: 'Skip smoke tests'
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: '20'
  AWS_REGION: us-east-1

jobs:
  # ===========================================================================
  # Build Lambda Package
  # ===========================================================================
  build:
    name: Build Lambda Package
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-name }}
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: infrastructure/lambda/forge-worker/package-lock.json

      - name: Generate version
        id: version
        run: |
          VERSION="${{ github.sha }}-$(date +%Y%m%d%H%M%S)"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        working-directory: infrastructure/lambda/forge-worker
        run: npm ci

      - name: TypeScript compile
        working-directory: infrastructure/lambda/forge-worker
        run: npm run build

      - name: Run tests
        working-directory: infrastructure/lambda/forge-worker
        run: npm test || echo "Tests skipped (no tests configured)"

      - name: Prune dev dependencies
        working-directory: infrastructure/lambda/forge-worker
        run: npm prune --production

      - name: Create deployment package
        working-directory: infrastructure/lambda/forge-worker
        run: |
          zip -r ../forge-worker-${{ steps.version.outputs.version }}.zip .
          ls -la ../

      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: forge-worker-${{ steps.version.outputs.version }}
          path: infrastructure/lambda/forge-worker-*.zip
          retention-days: 30

  # ===========================================================================
  # Validate Terraform
  # ===========================================================================
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.0'

      - name: Terraform Format Check
        working-directory: infrastructure/terraform/modules/lambda
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: infrastructure/terraform/modules/lambda
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: infrastructure/terraform/modules/lambda
        run: terraform validate

  # ===========================================================================
  # Deploy to Staging
  # ===========================================================================
  deploy-staging:
    name: Deploy to Staging
    needs: [build, validate]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: forge-worker-${{ needs.build.outputs.version }}
          path: ./artifacts

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_STAGING }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 cp ./artifacts/forge-worker-*.zip \
            s3://${{ secrets.LAMBDA_BUCKET_STAGING }}/forge-worker/forge-worker.zip

      - name: Update Lambda Functions
        run: |
          # Update Convergence Worker
          aws lambda update-function-code \
            --function-name forge-convergence-worker-staging \
            --s3-bucket ${{ secrets.LAMBDA_BUCKET_STAGING }} \
            --s3-key forge-worker/forge-worker.zip \
            --publish

          # Update Parser Worker
          aws lambda update-function-code \
            --function-name forge-parser-worker-staging \
            --s3-bucket ${{ secrets.LAMBDA_BUCKET_STAGING }} \
            --s3-key forge-worker/forge-worker.zip \
            --publish

          # Update CARS Assessor
          aws lambda update-function-code \
            --function-name forge-cars-assessor-staging \
            --s3-bucket ${{ secrets.LAMBDA_BUCKET_STAGING }} \
            --s3-key forge-worker/forge-worker.zip \
            --publish

      - name: Wait for update
        run: |
          for fn in forge-convergence-worker-staging forge-parser-worker-staging forge-cars-assessor-staging; do
            aws lambda wait function-updated --function-name $fn
          done

      - name: Smoke Test
        if: ${{ github.event.inputs.skip_tests != 'true' }}
        run: |
          # Test convergence worker
          RESULT=$(aws lambda invoke \
            --function-name forge-convergence-worker-staging \
            --payload '{"action":"execute","payload":{"prompt":"Say hello","model":"haiku","maxTokens":100}}' \
            --cli-binary-format raw-in-base64-out \
            response.json)

          cat response.json

          if [ "$(jq -r '.success' response.json)" != "true" ]; then
            echo "Smoke test failed!"
            exit 1
          fi

      - name: Update alias to new version
        run: |
          for fn in forge-convergence-worker-staging forge-parser-worker-staging forge-cars-assessor-staging; do
            VERSION=$(aws lambda publish-version --function-name $fn --query 'Version' --output text)
            aws lambda update-alias \
              --function-name $fn \
              --name live \
              --function-version $VERSION
          done

  # ===========================================================================
  # Deploy to Production
  # ===========================================================================
  deploy-prod:
    name: Deploy to Production
    needs: [build, validate, deploy-staging]
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: forge-worker-${{ needs.build.outputs.version }}
          path: ./artifacts

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_PROD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Store previous versions for rollback
        id: previous
        run: |
          for fn in forge-convergence-worker-prod forge-parser-worker-prod forge-cars-assessor-prod; do
            VERSION=$(aws lambda get-alias --function-name $fn --name live --query 'FunctionVersion' --output text)
            echo "${fn}_VERSION=${VERSION}" >> $GITHUB_OUTPUT
          done

      - name: Upload to S3
        run: |
          aws s3 cp ./artifacts/forge-worker-*.zip \
            s3://${{ secrets.LAMBDA_BUCKET_PROD }}/forge-worker/forge-worker.zip

      - name: Update Lambda Functions
        id: update
        run: |
          for fn in forge-convergence-worker-prod forge-parser-worker-prod forge-cars-assessor-prod; do
            aws lambda update-function-code \
              --function-name $fn \
              --s3-bucket ${{ secrets.LAMBDA_BUCKET_PROD }} \
              --s3-key forge-worker/forge-worker.zip \
              --publish
          done

      - name: Wait for update
        run: |
          for fn in forge-convergence-worker-prod forge-parser-worker-prod forge-cars-assessor-prod; do
            aws lambda wait function-updated --function-name $fn
          done

      - name: Production Smoke Test
        id: smoketest
        if: ${{ github.event.inputs.skip_tests != 'true' }}
        run: |
          RESULT=$(aws lambda invoke \
            --function-name forge-convergence-worker-prod \
            --payload '{"action":"execute","payload":{"prompt":"Say hello","model":"haiku","maxTokens":100}}' \
            --cli-binary-format raw-in-base64-out \
            response.json)

          cat response.json

          if [ "$(jq -r '.success' response.json)" != "true" ]; then
            echo "::error::Production smoke test failed!"
            echo "test_failed=true" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Update production aliases
        if: steps.smoketest.outcome == 'success' || github.event.inputs.skip_tests == 'true'
        run: |
          for fn in forge-convergence-worker-prod forge-parser-worker-prod forge-cars-assessor-prod; do
            VERSION=$(aws lambda list-versions-by-function --function-name $fn --query 'Versions[-1].Version' --output text)
            aws lambda update-alias \
              --function-name $fn \
              --name live \
              --function-version $VERSION
          done

      - name: Rollback on failure
        if: failure() && steps.update.outcome == 'success'
        run: |
          echo "Rolling back to previous versions..."

          aws lambda update-alias \
            --function-name forge-convergence-worker-prod \
            --name live \
            --function-version ${{ steps.previous.outputs.forge-convergence-worker-prod_VERSION }}

          aws lambda update-alias \
            --function-name forge-parser-worker-prod \
            --name live \
            --function-version ${{ steps.previous.outputs.forge-parser-worker-prod_VERSION }}

          aws lambda update-alias \
            --function-name forge-cars-assessor-prod \
            --name live \
            --function-version ${{ steps.previous.outputs.forge-cars-assessor-prod_VERSION }}

          echo "::error::Deployment failed and was rolled back!"

  # ===========================================================================
  # Notify
  # ===========================================================================
  notify:
    name: Notify
    needs: [build, deploy-staging]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1
        if: env.SLACK_WEBHOOK_URL != ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "text": "FORGE Lambda Deployment: ${{ needs.deploy-staging.result == 'success' && 'SUCCESS' || 'FAILED' }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "FORGE Lambda Deployment"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {"type": "mrkdwn", "text": "*Status:*\n${{ needs.deploy-staging.result == 'success' && ':white_check_mark: Success' || ':x: Failed' }}"},
                    {"type": "mrkdwn", "text": "*Version:*\n${{ needs.build.outputs.version }}"},
                    {"type": "mrkdwn", "text": "*Branch:*\n${{ github.ref_name }}"},
                    {"type": "mrkdwn", "text": "*Actor:*\n${{ github.actor }}"}
                  ]
                }
              ]
            }
